# Generated by Django 3.2.4 on 2022-03-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0009_auto_20211027_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
