# Generated by Django 3.2.4 on 2022-03-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0010_alter_blogmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='bg_color_code',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='image_tree',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='image_two',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='more',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='read_time',
        ),
    ]
