# Generated by Django 3.2.4 on 2022-03-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0011_auto_20220302_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='ana resim "1200x840"'),
        ),
    ]
