# Generated by Django 3.2.4 on 2022-03-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0012_auto_20220302_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['title'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
