# Generated by Django 3.2.4 on 2022-03-02 22:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0013_alter_blogmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='intro_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='intro_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='başlık'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='başlık'),
        ),
    ]
