# Generated by Django 3.2.4 on 2022-03-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0014_auto_20220303_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='intro_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_en',
        ),
    ]
