# Generated by Django 3.2.4 on 2022-03-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0016_blogmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='intro_fr',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_fr',
        ),
    ]
